#!/bin/sh
if [ -f /var/www/localhost/htdocs/data/.ocdata ]; then
	occ upgrade
else
	occ maintenance:install --database=mysql --database-name=nextcloud --database-user=nextcloud --database-pass='' --admin-user=admin --admin-pass=admin
	occ config:system:delete trusted_domains
	occ config:system:set trusted_domains 1 --value='*'
fi
