#!/bin/sh
if [ ! -f /run/initramfs/boot/system.swp ]; then
  echo "Creating swap file..."
  truncate -s 1G system.swp && mkswap system.swp
  mv system.swp /run/initramfs/boot/
fi

if [ ! -f /run/initramfs/boot/system.dat ]; then
  echo "Creating data file..."
  truncate -s 1G system.dat && mkfs.xfs system.dat
  mv system.dat /run/initramfs/boot/
fi

sync
echo "Done. Reboot system to take effects."
