#!/bin/sh
BOOTDIR=/run/initramfs/boot
SELF=$(findmnt -ln -o SOURCE $BOOTDIR)
if [ ! -b "$SELF" ]; then
  echo "Device for boot partition could not be determined."
  exit 1
fi

DEVICE=$(lsblk -n -o PKNAME $SELF)

if [ -n "$DEVICE" ]; then
  DEVICE=/dev/$DEVICE
else
  DEVICE=$SELF
fi

PTTYPE=$(lsblk -dn -o PTTYPE $DEVICE)

if [ -n "$PTTYPE" -a "$PTTYPE" != "dos" ]; then
  echo "This device is not BIOS compatible."
  exit 1
fi

mkdir -p $BOOTDIR/boot/grub
echo -e 'insmod echo\ninsmod linux\nsource /system.cfg\nset BOOT_PARTITION=$root\nloopback loop /system.img\nset root=loop\nset prefix=($root)/boot/grub\nnormal' > $BOOTDIR/boot/grub/grub.cfg
grub-install --target=i386-pc --recheck --boot-directory=$BOOTDIR/boot \
    --modules="xfs fat part_msdos normal linux echo all_video test multiboot2 search sleep gzio lvm chain configfile cpuid minicmd gfxterm font terminal squash4 loopback videoinfo videotest blocklist probe" \
    $DEVICE

echo "Done."
