import {pkg} from "./collect.ts"

pkg("dev-python/jinja")
pkg("dev-python/httplib2")
pkg("dev-python/netaddr")
pkg("net-misc/sshpass")
pkg("dev-python/pyparsing")
pkg("dev-python/ptyprocess")
pkg("dev-python/ply")
pkg("dev-python/pyasn1")
pkg("dev-libs/libsodium")
pkg("dev-python/pexpect")
pkg("dev-python/packaging")
pkg("dev-python/pycparser")
pkg("dev-python/cffi")
pkg("dev-python/cryptography")
pkg("dev-python/bcrypt")
pkg("dev-python/pynacl")
pkg("dev-python/paramiko")
pkg("app-admin/ansible")
