#!/bin/sh
mount -t proc -o noexec,nosuid,nodev proc /proc >/dev/null 2>&1
CMDLINE=$(cat /proc/cmdline)

CONSOLE='/dev/console'

splash() {
	return 0
}

[ -e /usr/share/splashutils/initrd.splash ] && . /usr/share/splashutils/initrd.splash

# Clean input/output
exec >${CONSOLE} <${CONSOLE} 2>&1

LOCALE='ja_JP'

for x in ${CMDLINE}
do
	case "${x}" in
		walbrix.locale=*)
			LOCALE=${x#*=}
		;;
	esac
done

splash 'init'

umount /proc  # this can't be done before the first call to 'splash' function

mount -o remount,rw / >/dev/null 2>&1

if [ -n "$LOCALE" ]; then
    cp -a /.locale/$LOCALE/. /
fi

exec /sbin/init $@
