#!/bin/sh
WBUI_BASE=/usr/share/wbui

[ $# -eq 0 ] && PYTHONPATH=${WBUI_BASE} exec python2.7 -m cli2

PYTHON_MODULE=`echo $1 | sed 's/-/_/g'`

if [ "$PYTHON_MODULE" = "import" ]; then
    PYTHON_MODULE="import_vm"
fi

if [ -f ${WBUI_BASE}/cli2/${PYTHON_MODULE}.py -o -f ${WBUI_BASE}/cli2/${PYTHON_MODULE}.pyc ]; then
    shift
    PYTHONPATH=${WBUI_BASE} exec python2.7 -m cli2.${PYTHON_MODULE} $@
fi

#else (for backward compatibility)
exec /usr/bin/python2.7 ${WBUI_BASE}/wb.pyc $@
