#!/sbin/runscript
PIDFILE=/var/run/${SVCNAME}.pid
LOGFILE=/var/log/hubot/${SVCNAME}.log

depend() {
	use dns net
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --make-pidfile -b --exec "/bin/bash" -d "${HUBOT_DIR}" \
		--user hubot --pidfile "${PIDFILE}" -- \
		-c "exec ${HUBOT_DIR}/bin/hubot ${HUBOT_OPTS} >> ${LOGFILE} 2>&1"
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile "${PIDFILE}"
	eend $?
}
