#!/bin/sh
PORT=2222
IF_NAME=$(awk '{ if ($2=="00000000") print $1}' /proc/net/route)
if [ -n "$IF_NAME" ]; then
  IP_ADDRESS=$(ip -4 addr show $IF_NAME | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
fi
SSHD_CONFIG=/tmp/$$_sshd_config
echo "Invoking ad-hoc sshd"
echo -e "Port $PORT\nPermitRootLogin yes\nPermitEmptyPasswords yes" > $SSHD_CONFIG
echo "Do"
[ -n "$IP_ADDRESS" ] && echo -e "\t\"ssh -p $PORT root@$IP_ADDRESS\"\nor"
echo -e "\t\"ssh -p $PORT root@`hostname`.local\"\nin other machine to login."
echo "Ctrl-C to stop"
/usr/sbin/sshd -D -f $SSHD_CONFIG
rm -f $SSHD_CONFIG
