#!/bin/sh
RW_ROOT=/.overlay/rw/root
DATA_FILE=/.overlay/boot/data.img

REQUIRED_CAPACITY=$(du -msx $RW_ROOT|cut -f 1)

if [ $REQUIRED_CAPACITY -lt 12 ]; then
  REQUIRED_CAPACITY=16
elif [ $REQUIRED_CAPACITY -lt 24 ]; then
  REQUIRED_CAPACITY=32
elif [ $REQUIRED_CAPACITY -lt 48 ]; then
  REQUIRED_CAPACITY=64
elif [ $REQUIRED_CAPACITY -lt 96 ]; then
  REQUIRED_CAPACITY=128
elif [ $REQUIRED_CAPACITY -lt 192 ]; then
  REQUIRED_CAPACITY=256
elif [ $REQUIRED_CAPACITY -lt 384 ]; then
  REQUIRED_CAPACITY=512
elif [ $REQUIRED_CAPACITY -lt 768 ]; then
  REQUIRED_CAPACITY=1024
else
  REQUIRED_CAPACITY=2048 # Max 2GB
fi

if [ -f "$DATA_FILE" ]; then
  DATA_FILE_CAPACITY=$(du -m $DATA_FILE|cut -f 1)
else
  DATA_FILE_CAPACITY=0
fi

mount -o remount,rw /.overlay/boot || exit 1
if [ $DATA_FILE_CAPACITY -lt $REQUIRED_CAPACITY ]; then
  echo "Preparing data file (may take while) ..."
  dd if=/dev/zero of="$DATA_FILE" bs=1M count=$(($REQUIRED_CAPACITY-$DATA_FILE_CAPACITY)) oflag=append conv=notrunc || exit 1
  if [ $DATA_FILE_CAPACITY -eq 0 ];then
    mkfs.xfs -f "$DATA_FILE" || exit 1
  fi
fi

TMPDIR=$(mktemp -d)
if mount -o loop "$DATA_FILE" "$TMPDIR"; then
  xfs_growfs "$TMPDIR"
  rsync -avxX --delete-excluded --exclude='/tmp' --exclude='/.overlay' ${RW_ROOT}/ $TMPDIR/ || echo "Rsync failed."
  sync

  umount "$TMPDIR" && rmdir "$TMPDIR" || echo "Unmounting loopback failed."
  sync
  mount -o remount,ro /.overlay/boot || echo "Remounting as R/O failed."
  echo "Done."
else
  rmdir "$TMPDIR"
  exit 1
fi
